### ISSUE TITLE
Dynamic CLR

### ISSUE THREAD

**Issue by rose-jinyang** [dallal9/keyphrase#1]
Hello
How are you?
Sorry to emit this issue here.
I read your blog "Exploring Super-Convergence" which explained an auto dynamic CLR method.
I could NOT find any source code for this method.
Could u share the code?
Thanks

**Comment by dallal9** [comment]
Hello, 
Sure, there is a public colab notebook available. https://colab.research.google.com/github/deepmipt/DeepPavlov/blob/master/examples/super_convergence_tutorial.ipynb
